<?php
if (!defined('ABSPATH')) {
    exit;
}

class APIAPU_SEO_Tools {
    
    private $seo_plugin;
    private $auto_hn;
    private $schema_org;
    
    public function __construct() {
        $settings = get_option('apiapu_settings', array());
        $this->seo_plugin = isset($settings['seo_plugin']) ? $settings['seo_plugin'] : 'none';
        $this->auto_hn = isset($settings['auto_hn']) ? (bool) $settings['auto_hn'] : true;
        $this->schema_org = isset($settings['schema_org']) ? (bool) $settings['schema_org'] : false;
        
        // Hook for frontend output
        if ($this->schema_org) {
            add_action('wp_head', array($this, 'output_frontend_schema'));
        }
    }

    public function output_frontend_schema() {
        if (!is_single()) {
            return;
        }

        // Garde-fou anti-doublon : si un plugin SEO majeur gère déjà le Schema.org
        // (Yoast, Rank Math, All In One SEO), on n'ajoute pas le nôtre pour éviter
        // un schéma "Article" dupliqué (avertissements Google Search Console).
        if (defined('WPSEO_VERSION') || class_exists('RankMath') || function_exists('aioseo')) {
            return;
        }

        global $post;
        
        if (!$post) {
            return;
        }
        
        $schema_json = get_post_meta($post->ID, '_apiapu_schema_org', true);
        
        if (!empty($schema_json)) {
            echo "\n<!-- Schema.org generated by WPAutoContent -->\n";
            echo '<script type="application/ld+json">' . $schema_json . '</script>';
            echo "\n";
        }
    }
    
    public function apply_seo_to_post($post_id, $seo_data) {
        $meta_title = isset($seo_data['meta_title']) ? sanitize_text_field($seo_data['meta_title']) : '';
        $meta_description = isset($seo_data['meta_description']) ? sanitize_text_field($seo_data['meta_description']) : '';
        $keyword = isset($seo_data['keyword']) ? sanitize_text_field($seo_data['keyword']) : '';
        
        update_post_meta($post_id, '_apiapu_meta_title', $meta_title);
        update_post_meta($post_id, '_apiapu_meta_description', $meta_description);
        update_post_meta($post_id, '_apiapu_focus_keyword', $keyword);
        
        switch ($this->seo_plugin) {
            case 'yoast':
                $this->apply_yoast_seo($post_id, $meta_title, $meta_description, $keyword);
                break;
            case 'rankmath':
                $this->apply_rankmath_seo($post_id, $meta_title, $meta_description, $keyword);
                break;
            case 'aioseo':
                $this->apply_aioseo($post_id, $meta_title, $meta_description, $keyword);
                break;
        }
        
        if ($this->schema_org) {
            $this->add_schema_org($post_id, $seo_data);
        }
        
        APIAPU_Logger::log("SEO appliqué pour post {$post_id}", 'success', array('post_id' => $post_id));
    }
    
    private function apply_yoast_seo($post_id, $meta_title, $meta_description, $keyword) {
        if (!defined('WPSEO_VERSION')) {
            APIAPU_Logger::log('Yoast SEO non installé', 'warning');
            return;
        }
        
        update_post_meta($post_id, '_yoast_wpseo_title', $meta_title);
        update_post_meta($post_id, '_yoast_wpseo_metadesc', $meta_description);
        update_post_meta($post_id, '_yoast_wpseo_focuskw', $keyword);
        
        APIAPU_Logger::log('Yoast SEO meta appliqué', 'info', array('post_id' => $post_id));
    }
    
    private function apply_rankmath_seo($post_id, $meta_title, $meta_description, $keyword) {
        if (!class_exists('RankMath')) {
            APIAPU_Logger::log('Rank Math non installé', 'warning');
            return;
        }
        
        update_post_meta($post_id, 'rank_math_title', $meta_title);
        update_post_meta($post_id, 'rank_math_description', $meta_description);
        update_post_meta($post_id, 'rank_math_focus_keyword', $keyword);
        
        APIAPU_Logger::log('Rank Math meta appliqué', 'info', array('post_id' => $post_id));
    }
    
    private function apply_aioseo($post_id, $meta_title, $meta_description, $keyword) {
        if (!function_exists('aioseo')) {
            APIAPU_Logger::log('All In One SEO non installé', 'warning');
            return;
        }
        
        update_post_meta($post_id, '_aioseo_title', $meta_title);
        update_post_meta($post_id, '_aioseo_description', $meta_description);
        update_post_meta($post_id, '_aioseo_keywords', $keyword);
        
        APIAPU_Logger::log('All In One SEO meta appliqué', 'info', array('post_id' => $post_id));
    }
    
    public function optimize_headings($content, $title = '') {
        if (!$this->auto_hn) {
            return $content;
        }

        // SEO : le titre de l'article (post_title) est déjà rendu en <h1> par le thème.
        // Pour éviter un double H1 (pénalisant pour le référencement), on rétrograde
        // tout <h1> présent dans le contenu généré en <h2>.
        $content = preg_replace('/<(\/?)h1\b([^>]*)>/i', '<$1h2$2>', $content);

        // Ajout d'ancres (IDs) aux sous-titres H2-H6 qui n'en ont pas.
        $content = preg_replace_callback(
            '/<h([2-6])([^>]*)>(.*?)<\/h\1>/is',
            function($matches) {
                $level = $matches[1];
                $attrs = $matches[2];
                $text = $matches[3];

                if (strpos($attrs, 'id=') === false) {
                    $id = sanitize_title($text);
                    if (!empty($id)) {
                        $attrs .= ' id="' . $id . '"';
                    }
                }

                return "<h{$level}{$attrs}>{$text}</h{$level}>";
            },
            $content
        );

        return $content;
    }
    
    public function add_schema_org($post_id, $seo_data) {
        $post = get_post($post_id);
        
        if (!$post) {
            return;
        }
        
        $schema = array(
            '@context' => 'https://schema.org',
            '@type' => 'Article',
            'headline' => $post->post_title,
            'description' => isset($seo_data['meta_description']) ? $seo_data['meta_description'] : '',
            'datePublished' => get_the_date('c', $post_id),
            'dateModified' => get_the_modified_date('c', $post_id),
            'author' => array(
                '@type' => 'Person',
                'name' => get_the_author_meta('display_name', $post->post_author),
            ),
            'publisher' => array(
                '@type' => 'Organization',
                'name' => get_bloginfo('name'),
                'url' => home_url(),
            ),
            'mainEntityOfPage' => array(
                '@type' => 'WebPage',
                '@id' => get_permalink($post_id),
            ),
        );
        
        if (has_post_thumbnail($post_id)) {
            $schema['image'] = array(
                '@type' => 'ImageObject',
                'url' => get_the_post_thumbnail_url($post_id, 'full'),
            );
        }
        
        update_post_meta($post_id, '_apiapu_schema_org', wp_json_encode($schema));
        
        APIAPU_Logger::log('Schema.org ajouté', 'info', array('post_id' => $post_id));
    }
    
    public function generate_slug($title) {
        $slug = sanitize_title($title);
        $slug = substr($slug, 0, 60);
        $slug = rtrim($slug, '-');
        
        return $slug;
    }
    
    public function generate_meta_title($title, $keyword = '') {
        $meta_title = $title;
        
        if (strlen($meta_title) > 60) {
            $meta_title = substr($meta_title, 0, 57) . '...';
        }
        
        return $meta_title;
    }
    
    public function generate_meta_description($content, $keyword = '') {
        $text = wp_strip_all_tags($content);
        $text = preg_replace('/\s+/', ' ', $text);
        
        if (strlen($text) > 155) {
            $text = substr($text, 0, 152) . '...';
        }
        
        return $text;
    }
    
    public function get_seo_score($post_id) {
        $content = get_post_field('post_content', $post_id);
        $title = get_the_title($post_id);
        $keyword = get_post_meta($post_id, '_apiapu_focus_keyword', true);
        
        $score = 0;
        $checks = array();
        
        if (!empty($keyword) && stripos($title, $keyword) !== false) {
            $score += 20;
            $checks['keyword_in_title'] = true;
        } else {
            $checks['keyword_in_title'] = false;
        }
        
        $word_count = str_word_count(wp_strip_all_tags($content));
        if ($word_count >= 800) {
            $score += 20;
            $checks['word_count'] = true;
        } else {
            $checks['word_count'] = false;
        }
        
        if (preg_match_all('/<h[2-3][^>]*>/i', $content) >= 2) {
            $score += 15;
            $checks['headings'] = true;
        } else {
            $checks['headings'] = false;
        }
        
        if (has_post_thumbnail($post_id)) {
            $score += 15;
            $checks['featured_image'] = true;
        } else {
            $checks['featured_image'] = false;
        }
        
        $meta_title = get_post_meta($post_id, '_apiapu_meta_title', true);
        if (!empty($meta_title) && strlen($meta_title) <= 60) {
            $score += 15;
            $checks['meta_title'] = true;
        } else {
            $checks['meta_title'] = false;
        }
        
        $meta_desc = get_post_meta($post_id, '_apiapu_meta_description', true);
        if (!empty($meta_desc) && strlen($meta_desc) <= 155) {
            $score += 15;
            $checks['meta_description'] = true;
        } else {
            $checks['meta_description'] = false;
        }
        
        return array(
            'score' => $score,
            'checks' => $checks,
        );
    }
}
